version: '3'
services:
  apigateway:
    image: apigateway:1.0.0
    container_name: apigateway
    ports:
      - 8080:8080
    environment:
      LOG_LEVEL: debug
      CONSUL_ADDR: consul:8500
      ZIPKIN_ADDR: zipkin:9411
    depends_on:
      - consul
      - userservice
      - zipkin
  staticservice:
    image: staticservice:1.0.0
    container_name: staticservice
    ports:
      - 4900:4900
      - 9000:9000
    environment:
      CONFIG_FILE: configs/staticservice/dev.toml
      LOG_LEVEL: debug
    volumes:
      - ./configs/:/data/configs/
    depends_on:
      - zipkin
      - mysql
      - consul
  institutionservice:
    image: institutionservice:1.0.0
    container_name: institutionservice
    ports:
      - 4800:4800
    environment:
      CONFIG_FILE: configs/institutionservice/dev.toml
      LOG_LEVEL: debug
    volumes:
      - ./configs/:/data/configs/
    depends_on:
      - zipkin
      - mysql
      - consul
  userservice:
    image: userservice:1.0.0
    container_name: userservice
    ports:
      - 5000:5000
    environment:
      CONFIG_FILE: configs/dev.toml
      LOG_LEVEL: debug
      ZIPKIN_ADDR: zipkin:9411
    depends_on:
      - redis
      - consul
      - zipkin
    #command: ['sleep', '200000']
    volumes:
      - ./configs/userservice/:/data/configs
  swagger:
    image: swaggerapi/swagger-ui:v3.22.1
    container_name: swagger
    ports:
      - 8088:8080
  redis:
    image: redis:5.0.4
    container_name: redis
    ports:
      - 6379:6379
  consul:
    image: consul:1.4.4
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600
    command: '{"skip_leave_on_interrupt": true}'
  nginx:
    image: nginx:1.16
    container_name: nginx
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/conf/:/etc/nginx/
      - ./app/:/app/
