rbacFile = "configs/rbac.conf"

[db]
[db.mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
db = "apsmgm"

[db.redis]
host = "127.0.0.1"
port = 6379

[grpc]
host = "127.0.0.1"
port = 5000

[consul]
host = "127.0.0.1"
port = 8500

[watcher]
addr = "0.0.0.0:9000"

[task]
cron = "0 * * * * *"
