// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/user.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserRequest struct {
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *GetUserRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetUserResponse struct {
	V                    *UserRecord `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Err                  string      `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetV() *UserRecord {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *GetUserResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *RegisterRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	User                 *UserRecord `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string      `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Err                  string      `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *UserRecord {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UserRecord struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Salt                 string   `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
	Userid               string   `protobuf:"bytes,7,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRecord) Reset()         { *m = UserRecord{} }
func (m *UserRecord) String() string { return proto.CompactTextString(m) }
func (*UserRecord) ProtoMessage()    {}
func (*UserRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{6}
}

func (m *UserRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRecord.Unmarshal(m, b)
}
func (m *UserRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRecord.Marshal(b, m, deterministic)
}
func (m *UserRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRecord.Merge(m, src)
}
func (m *UserRecord) XXX_Size() int {
	return xxx_messageInfo_UserRecord.Size(m)
}
func (m *UserRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRecord.DiscardUnknown(m)
}

var xxx_messageInfo_UserRecord proto.InternalMessageInfo

func (m *UserRecord) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UserRecord) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *UserRecord) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRecord) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRecord) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRecord) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *UserRecord) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "pb.GetUserResponse")
	proto.RegisterType((*RegisterRequest)(nil), "pb.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "pb.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterType((*UserRecord)(nil), "pb.UserRecord")
}

func init() {
	proto.RegisterFile("pb/user.proto", fileDescriptor_c4f917211a932270)
}

var fileDescriptor_c4f917211a932270 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xbb, 0x4e, 0xeb, 0x40,
	0x10, 0xbd, 0x6b, 0xe7, 0x39, 0x97, 0x38, 0x61, 0x89, 0x90, 0x65, 0xa5, 0x88, 0x5c, 0xa5, 0x32,
	0x52, 0x88, 0x44, 0x43, 0x43, 0x03, 0x0d, 0x95, 0x11, 0x15, 0x95, 0x1d, 0x0f, 0xd1, 0x8a, 0xc4,
	0x36, 0xbb, 0x4e, 0x90, 0xf8, 0x13, 0xbe, 0x82, 0x5f, 0xe0, 0xd3, 0xd0, 0xae, 0xd7, 0x4f, 0x01,
	0x82, 0x6e, 0xe7, 0x71, 0x66, 0xe6, 0x9c, 0x99, 0x85, 0x51, 0x1a, 0x9e, 0xed, 0x05, 0x72, 0x2f,
	0xe5, 0x49, 0x96, 0x50, 0x23, 0x0d, 0xdd, 0x4b, 0xb0, 0x6e, 0x30, 0xbb, 0x17, 0xc8, 0x7d, 0x7c,
	0xde, 0xa3, 0xc8, 0xe8, 0x29, 0xf4, 0x64, 0x0e, 0x8b, 0x6c, 0x32, 0x27, 0x8b, 0xa1, 0xaf, 0x2d,
	0x4a, 0xa1, 0x23, 0xd8, 0x2b, 0xda, 0xc6, 0x9c, 0x2c, 0x4c, 0x5f, 0xbd, 0xdd, 0x2b, 0x18, 0x97,
	0x68, 0x91, 0x26, 0xb1, 0x40, 0x3a, 0x03, 0x72, 0x50, 0xc8, 0xff, 0x4b, 0xcb, 0x4b, 0x43, 0x2f,
	0x0f, 0xae, 0x13, 0x1e, 0xf9, 0xe4, 0x40, 0x27, 0x60, 0x22, 0xe7, 0xaa, 0xc6, 0xd0, 0x97, 0x4f,
	0xf7, 0x8d, 0xc0, 0xd8, 0xc7, 0x0d, 0x13, 0x59, 0x35, 0x82, 0x03, 0x03, 0xd9, 0x34, 0x0e, 0x76,
	0xa8, 0x87, 0x28, 0x6d, 0x3a, 0x83, 0xe1, 0x23, 0xe3, 0x22, 0x53, 0xc1, 0xbc, 0x4e, 0xe5, 0x90,
	0xc8, 0x6d, 0xa0, 0x83, 0x66, 0x8e, 0x2c, 0x6c, 0x3a, 0x85, 0x2e, 0xee, 0x02, 0xb6, 0xb5, 0x3b,
	0x2a, 0x90, 0x1b, 0x12, 0x91, 0x06, 0x42, 0xbc, 0x24, 0x3c, 0xb2, 0xbb, 0x39, 0xa2, 0xb0, 0xdd,
	0x15, 0x4c, 0xaa, 0xd1, 0x34, 0x3f, 0x0b, 0x8c, 0x52, 0x1a, 0x83, 0x45, 0x5f, 0x30, 0xba, 0x86,
	0xa3, 0xdb, 0x64, 0xc3, 0xe2, 0xdf, 0xb0, 0xa9, 0x77, 0x37, 0x5a, 0xdd, 0x1f, 0x60, 0xa4, 0xeb,
	0xe8, 0xd6, 0x2e, 0x74, 0x24, 0xf0, 0x1b, 0x75, 0x55, 0x4c, 0x92, 0xcc, 0x92, 0x27, 0x8c, 0x75,
	0xb5, 0xdc, 0x28, 0x86, 0x34, 0xab, 0x21, 0x3f, 0x08, 0x40, 0x05, 0x6e, 0xaa, 0x4a, 0x7e, 0x52,
	0xd5, 0x68, 0xa9, 0x5a, 0x67, 0x67, 0xb6, 0xd8, 0xfd, 0x59, 0x71, 0x75, 0x64, 0xc1, 0x36, 0xb3,
	0x7b, 0xca, 0xaf, 0xde, 0xb5, 0x83, 0xec, 0xd7, 0x0f, 0x72, 0xf9, 0x4e, 0xc0, 0x52, 0x14, 0xd2,
	0xf5, 0x1d, 0xf2, 0x03, 0x5b, 0x23, 0x5d, 0x41, 0x5f, 0xdf, 0x23, 0xa5, 0x52, 0x9e, 0xe6, 0x69,
	0x3b, 0x27, 0x0d, 0x5f, 0xae, 0xaa, 0xfb, 0x8f, 0x5e, 0xc0, 0xa0, 0x58, 0x33, 0x55, 0x29, 0xad,
	0x7b, 0x74, 0xa6, 0x4d, 0x67, 0x09, 0xf4, 0xa0, 0xab, 0x36, 0x44, 0x27, 0x32, 0xa1, 0xbe, 0x74,
	0xe7, 0xb8, 0xe6, 0x29, 0xf2, 0xc3, 0x9e, 0xfa, 0x77, 0xe7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x53, 0x3c, 0x79, 0xbc, 0x88, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserRpcServiceClient is the client API for UserRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserRpcServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcServiceClient(cc grpc.ClientConnInterface) UserRpcServiceClient {
	return &userRpcServiceClient{cc}
}

func (c *userRpcServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/pb.UserRpcService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/pb.UserRpcService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.UserRpcService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServiceServer is the server API for UserRpcService service.
type UserRpcServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedUserRpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserRpcServiceServer struct {
}

func (*UnimplementedUserRpcServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserRpcServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserRpcServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterUserRpcServiceServer(s *grpc.Server, srv UserRpcServiceServer) {
	s.RegisterService(&_UserRpcService_serviceDesc, srv)
}

func _UserRpcService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserRpcService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpcService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserRpcService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpcService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserRpcService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserRpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserRpcService",
	HandlerType: (*UserRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserRpcService_GetUser_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserRpcService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserRpcService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/user.proto",
}
