[db]
[db.mysql]
host = "172.17.0.1"
port = 3306
user = "test"
password = "test"
db = "apsmgm"
[db.redis]
host = "127.0.0.1"
port = 6379

[grpc]
host = "0.0.0.0"
port = 4900
registHost = "staticservice"
registPost = 4900

[consul]
host = "172.17.0.1"
port = 8500

[watcher]
addr = "0.0.0.0:9000"

[info]
serviceName = "staticService"